const guestList = [
  "PEDRO ROMERO",
  "DARIO GARZON",
  "FELIPE RODRIGUEZ",
  "RICARDO CORREDOR",
  "PABLO ORJUELA",
  "RICARDO MONTANER",
  "CAROLINA CACUA",
  "MARIO BROS",
  "PRINCESA PEACH",
  "GILBERTO SANTA ROSA",
  "VICENTE FERNANDEZ",
];

export default guestList;
